### ISSUE TITLE
"Task updated successfully" message is displaying when the user clicks back while creating a task.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#152]
Environment:- Windows 7
Module: Create  Task
Credentials :- [[john_k@mailinator.com]/11111111
Priority: Normal

Steps to reproduce:-
1. Open Javul Site and log in with valid credentials.
2. Click on tasks
3. Click on add tasks
4  It will navigate to the create task
5  Click on create a task without entering any fields
6  Now click back 
7  Observe 

Actual result: "Task updated successfully" message is displaying when the user click back when a user tries to create tasks.
Expected result: "Task updated successfully"message should not be displayed.

Video URL : https://drive.google.com/file/d/1D0NqIRf3Y3Xc6vkWkM9m1-0xk8sYpM7C/view?usp=sharing

**Comment by acipher** [comment]
Unable to reproduce. @javulorg can you please confirm this?

**Comment by javulorg** [comment]
Actually I would like to remove the 'Add Tasks' button from that page view: http://javul.org/tasks
The reason is that we only want people to add tasks from within the Unit they are working in. After thats done, this issue can be closed.
I did test this issue via the Units and Objectives interface and it worked fine for those interfaces.

**Comment by acipher** [comment]
**Add Tasks** button removed.
