### ISSUE TITLE
Search by skills and search by status both the search fields are not working the same.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#156]
Environment:- Windows 7
Module: Create  Task
Credentials :- [[john_k@mailinator.com]/11111111
Priority: Normal

Steps to reproduce:-
1. Open Javul Site and log in with valid credentials.
2. Click on tasks
3 Go to search by skills and search by status

Actual result: Search by skills and search by status both the search fields are not working the same.
Excepted result: Search by skills and search by status both the search fields should work the same.

https://drive.google.com/file/d/1yqBS-d3a8U2CfuFmAJjoL9sVJDSVUI4s/view?usp=sharing

**Comment by acipher** [comment]
@javulorg can you please explain the issue?. Search seems to be working for us. Please validate.

**Comment by javulorg** [comment]
Ok I see what they mean. https://javul.org/tasks
Currently, when I type in 's' in the 'search by skill' field, it only searches for any skills starting with the letter 's'.
When I  type in 's' in 'search by status' field, it searches for any skills where the letter can be in any position, not just the first letter.

Desired behavior:

Search by skill: Leave unchanged  (for now; we might revisit this later)

Search by status: Remove search ability for this field and change this selection to a drop-down of all the possible values of Task status, sorted by the order they appear in the Task management system e.g. Editable, Waiting for Approval, Open for Bidding, ......, Completed, Cancelled. 
The reason is that Task status will always be a limited number of options and so we can just show those options to the user so they wont have to type anything.

**Comment by acipher** [comment]
Showing task status as drop-down can you please confirm @javulorg , if this approve then can you please close this issue.

![image](https://user-images.githubusercontent.com/3071346/54339619-690def80-465b-11e9-94a3-2a64aa9a1765.png)

**Comment by javulorg** [comment]
Looks good. Can you swap 'Awaiting Assignment' and 'Assigned'? And then this can be closed.

**Comment by acipher** [comment]
@javulorg we have sort statuses in ascending order. will this work?

![image](https://user-images.githubusercontent.com/3071346/54509742-923ac280-4970-11e9-89a7-216e5975ca18.png)

**Comment by javulorg** [comment]
Sure thats fine. Maybe thats the best option. Closing this.
