### ISSUE TITLE
Mobile View updates

### ISSUE THREAD

**Issue by javulorg** [javulorg/javul#16]
- For some pages (main page, Individual Item pages like Objective, Task, Issue). Change Order of sections so that Activity log for a Unit is collapsed and is shown at the end of all other page content instead of being the first item. So it should look like this: Main Item information and other related items and at the end show Collapsed ‘Unit Information’ table and then collapsed ‘Unit Activity log’.
- When visiting any Unit home page, in the ‘Unit Information’ table, the font size of links for Objectives, Tasks Issues is smaller than the rest of the links.

**Comment by acipher** [comment]
- When visiting any Unit home page, in the ‘Unit Information’ table, the font size of links for Objectives, Tasks Issues is smaller than the rest of the links.

Can you please send me the screenshot or can you please explain more. because i didn't found it. i have checked links and all text font in "Unit Information" table for Unit, Objective, task and issue page. all are same.

**Comment by javulorg** [comment]
Sure, here is a screenshot. I'm using Chrome on the desktop. If you just resize the window and make the window width narrow, it will switch to Mobile view and you can see it. I see the same if I use Chrome on the phone. Firefox on Desktop also shows the same.
![image](https://cloud.githubusercontent.com/assets/19337355/23287511/e654c552-fa0b-11e6-9cdd-150575291ffc.png)

http://javul.org/units/xyrYdGJZwA/test_6
So we want the size of those three links the same as the font size for the links 'Forum, Chat and Wiki'

**Comment by acipher** [comment]
- Changed the order of section
- Changed the font size of text 

Can you please review?
Please let me know if need to change.

**Comment by javulorg** [comment]
Thanks, closed.
