### ISSUE TITLE
User table: Add 'username' field

### ISSUE THREAD

**Issue by javulorg** [javulorg/javul#18]
Account Sign-up needs DB field ‘username’ (check live availability on signup, disallow usernames like admin, site admin, siteadmin, javuladmin,adminjavul, administration). People can login by username or email (auto detect). Both username and email fields must be unique in database. This may mean changes for Activity Logs or other site items.
In Log items and other public places, when we are displaying the User's information if there is no First name and Last name, then display Username. Otherwise display the First and Last name (which is the current method).
OR: Just display Username for all cases.

**Comment by acipher** [comment]
1) Added "Username" field ( unique ). 
2) allowed user to login using username or email.
3) changed username in site activity if user has username then it will take username otherwise it will take first name and last name of user.

FYI: username will not changed in old site activities.

as you said **This may mean changes for Activity Logs or other site items** other site items means where to show username. can you please tell me?

**Comment by javulorg** [comment]
I think that should work. Those changes you made should be able to fulfill the requirement in bold. I'm closing this issue. Thanks
