### ISSUE TITLE
Paypal security

### ISSUE THREAD

**Issue by javulorg** [javulorg/javul#23]
For example if payment is going to be released to user, how can we protect the system against hacking or unauthorized payment? For example does Paypal have any security options on the Paypal website so Site admin can login there with the Javul account and release payments?

**Comment by acipher** [comment]
"For example if payment is going to be released to user, how can we protect the system against hacking or unauthorized payment"

**Do you mean when user withdraw the money when they have balance? Currently user has to enter the PayPal email address in order to get the money from javul account to user PayPal account.

There is no inbuilt security come with PayPal end to authorize the correct payment to user from our system, as they just need PayPal email only. You can always check by using merchant account and see transactions on the PayPal. But on our system we can implement 2fa (2 factor authentication) functionality to achieve the security to avoid hacking or unauthorized payment.
**

**Comment by javulorg** [comment]
> Do you mean when user withdraw the money when they have balance?

When they have balance they can withdraw up to the full amount of the balance and thats ok (expected behavior). For hacks I'm thinking if someone has intentionally hacked the code somehow or used some exploit that has not been fixed and they are able to receive money that is not theirs.

> But on our system we can implement 2fa (2 factor authentication) functionality to achieve the security to avoid hacking or unauthorized payment.

Could you explain more about the 2fa?

**Comment by acipher** [comment]
2 Factor Authentication: (OTP)

- when user make any payment on site we will send *One Time Password* on his/her mobile number exist in database. (FYI: we have to make mobile number compulsory in db)

- when user register into system we will verify his/her mobile number into our system
  once mobile number successfully verified we will only allowed that user to make any payment(s).

- when user enter amount in donate page and click pay using paypal we will send OTP to registered mobile number once OTP matched. we will redirect user to gateway and he/she can make transaction.

- if user change registered mobile number. we need to verify that new mobile number into system.

FYI: we need third party for OTP. (2FA)

**Comment by javulorg** [comment]
Thanks for the information about the OTP feature. Its good for future reference. For now I'm deciding not to have this implemented so I will close this issue.
